### PR TITLE
Scratch.org

### PR DESCRIPTION
**Pull request by GarboMuffin**
Speculation based on upcoming maintenance and certificate transparency logs

### CODE REVIEW

**Comment by Secret-chest** [comment]
What's this? Is Scratch really changing their domain name?

**Comment by LilyMakesThings** [comment]
> What's this? Is Scratch really changing their domain name?

There's evidence to suggest they're moving to scratch.org, yes.

**Comment by GarboMuffin** [comment]
This is, as the PR notes, a speculative change based on [some public logs](https://crt.sh/?q=scratch.org) combined with the timing of [upcoming maintenance](https://turbowarp.org/august-2023-scratch-maintenance.html)

**Comment by GarboMuffin** [comment]
There is of course a real possibility that this never gets used, which is all good and well.

**Comment by CubesterYT** [comment]
image
Wow

**Pull request closed without merging**
