### PR TITLE
Replace security.txt with security.md

### PR DESCRIPTION
**Pull request by Time-dragon**
### Resolves

- Resolves nothing.

### Proposed Changes

GitHub Flavored Markdown is better than plain text.

### Reason for Changes

I want changes because GitHub Flavored Markdown is more superior than plain text.

### Test Coverage

None

### Browser Coverage

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [x] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by Time-dragon** [comment]
This is a draft, don't review it.

**Comment by Time-dragon** [comment]
Now ready for review.

**Comment by GarboMuffin** [comment]
security.txt is a standard and must have a very specific text-based format. https://securitytxt.org/

although, the build is broken so the file doesn't actually end up in the website so it's currently useless, but that's something else for me to fix

**Comment by Time-dragon** [comment]
> security.txt is a standard and must have a very specific text-based format. https://securitytxt.org/
> 
> although, the build is broken so the file doesn't actually end up in the website so it's currently useless, but that's something else for me to fix

thanks

**Pull request closed without merging**
