### PR TITLE
Put file .babelrc to folder .github

### PR DESCRIPTION
**Pull request by Time-dragon**
### Resolves

Resolves nothing

### Proposed Changes

Just moving the .babelrc file to the .github folder.

### Reason for Changes

It's better in my opinion

### CODE REVIEW

**Comment by Time-dragon** [comment]
draft don't review

**Comment by Time-dragon** [comment]
undrafted review please

**Comment by retronbv** [comment]
Pretty sure this will break Babel

**Comment by GarboMuffin** [comment]
Please stop making these useless PRs.

**Comment by GarboMuffin** [comment]
3 day block because this is the fourth invalid PR you've sent in the last week, the second in twenty minutes.

This one in particular will break babel.

**Comment by GarboMuffin** [comment]
Just a reminder: this is a passion project by an unpaid volunteer. This is not the place for you to learn how to use GitHub, sorry. I don't have time to deal with that.

I care a lot about my signal:noise ratio, and you've just been completely ruining it.

**Pull request closed without merging**
