### PR TITLE
Rename is-mobile.js to mobile-detect.js

### PR DESCRIPTION
**Pull request by Time-dragon**
### Proposed Changes

Renames is-mobile to mobile-detect

### Reason for Changes

The changes should be made because it sounds better.

### CODE REVIEW

**Comment by GarboMuffin** [comment]
no...

**Comment by Time-dragon** [comment]
> no...

why?

**Comment by GarboMuffin** [comment]
This won't even build properly because you didn't update the imports for this file

Please don't submit non-trivial JavaScript file changes if you haven't actually tried it locally. It just wastes my time.

Anways I think

```js
import isMobile from './is-mobile';
```

is better than

```js
import isMobile from './mobile-detect';
```

**Comment by GarboMuffin** [comment]
If you want to do local builds, read https://github.com/TurboWarp/scratch-gui/wiki/Getting-Started. It's all explained there.

**Pull request closed without merging**
